# Generated by Django 6.0.1 on 2026-01-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_options_recipe_updated_at'),
        ('users', '0002_alter_user_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrecipefavorite',
            options={'ordering': ('-added_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='userrecipefavorite',
            unique_together={('user', 'recipe')},
        ),
    ]
