# Generated by Django 6.0 on 2025-12-26 15:38

import django.core.validators
import django.db.models.deletion
import recipehub.apps.recipes.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('announcement_text', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=recipehub.apps.recipes.utils.recipe_photo_upload_to)),
                ('ingredients', models.TextField()),
                ('recipe_text', models.TextField(blank=True, help_text='The text of the recipe')),
                ('servings', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('cooking_time', models.IntegerField(blank=True, help_text='Cooking time in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('calories', models.IntegerField(blank=True, help_text='Calories per serving', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
