# Generated by Django 6.0 on 2026-01-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_ingredients_alter_recipe_servings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='approved',
        ),
        migrations.AddField(
            model_name='recipe',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('in_process', 'In Process')], default='in_process', max_length=20),
        ),
    ]
