# Generated by Django 6.0.1 on 2026-01-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_options_recipe_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='Enter each ingredient on a new line and in the following order: ingredient name - quantity'),
        ),
    ]
